env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_12_task:
  freebsd_instance:
    image: freebsd-12-1-release-amd64
  install_script:
    pkg install -y curl
  create_user_script:
    - pw useradd git
    - chown -R git:git .
  test_script:
    - curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T rOKvxQ6HBmvrMXrK5QNc9j Dei4TGVuhx2PVq1vT2yYlx
